import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from '../../i18n/request';
import { notFound } from 'next/navigation';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages(locale);
  if (!messages) {
    notFound();
  }
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html className="h-full bg-gray-50">
        <body
          className={`flex h-full flex-col px-10 ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className="flex-grow">{children}</main>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
